#! /usr/bin/env python3
# -*- coding: utf-8 -*-

import sys

class MyError(Exception): 
    # Constructor or Initializer 
    def __init__(self, value, mensaje): 
# se cargan los valores enviados en el error al propio a MyError 
# para poderlo utilizar en la sección except
        self.value = value
        self.msg=mensaje


def comparaFitxers(argv):

    try:
        if len(sys.argv) == 3:   # compruebo el número de parámetros, han de ser 3, nombre del progrma y nombre de los  2 fichero a comparar
           
            f1 = open('/home/nando/programacio/fitxers/'+sys.argv[1], 'r') 
            f2 = open('/home/nando/programacio/fitxers/'+sys.argv[2], 'r')   
        else:
            raise(MyError(len(sys.argv),"Has d'introduïr el nom de 2 arxius."))
        # Lanzo una excepción si se indica únicamente el nombre del fichero 
    except MyError as error: 
        print("Número de parámetros: ",error.value, "\nMensaje: ", error.msg)
    
    
    except FileNotFoundError:
        print("Algun dels fitxers no existeix!!")

    else:
        print("Comparando el contenido de los ficheros...")
        # por hacer bucle que compare dos ficheros
        cont = 0
        for linea1 in f1:
            for linea2 in f2:
                if linea1 != linea2:
                    for caracter1 in linea1:
                        for caracter2 in linea2:
                            if caracter1 != caracter2:
                                #posDiferencia = f1.tell()
                                print("El 1er carácter diferent és: ",caracter2, " en el byte ")


comparaFitxers(sys.argv)
